resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      outerApiCircuitBreaker:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 1
  retry:
    retry-aspect-order: 2
    instances:
      outerApiRetry:
        maxAttempts: 10
        waitDuration: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE